# ── Categorías ────────────────────────────────────────────────────────────────
CATEGORIES = [
    {"id": "all",       "label": "Todas"},
    {"id": "sierra",    "label": "Sierras"},
    {"id": "prensa",    "label": "Prensas"},
    {"id": "acabado",   "label": "Acabado"},
    {"id": "medicion",  "label": "Medición"},
    {"id": "cnc",       "label": "CNC / Digital"},
    {"id": "furadeira", "label": "Furadeiras"},
]

MACHINES = [
    {"id": 1, "name": "Cepillo de Superficie", "generic": "Cepillo", "category": "acabado", "icon": "🪵", "color": "#C4956A", "desc": "Alisa y nivela la superficie de tablas de madera. Ideal para obtener superficies planas y uniformes antes del ensamble.", "tags": ["Acabado", "Superficie"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 2, "name": "CNC para Diseño", "generic": "CNC para Tableros", "category": "cnc", "icon": "🖥️", "color": "#4A7C2F", "desc": "Router CNC de alta precisión para corte y grabado en tableros. Control computarizado para diseños complejos.", "tags": ["CNC", "Digital", "Diseño"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 3, "name": "Encoladora", "generic": "Encoladora", "category": "acabado", "icon": "📏", "color": "#8B5E3C", "desc": "Aplica cola de manera uniforme en cantos y superficies de tableros. Esencial para enchapado y laminado.", "tags": ["Encolar", "Canteado"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 4, "name": "Escoplo", "generic": "Escoplo con Mesa Móvil", "category": "acabado", "icon": "🔨", "color": "#5C3D1E", "desc": "Mortajadora para hacer cajas y mortajas con precisión. Incluye mesa móvil para mayor versatilidad.", "tags": ["Mortaja", "Ensamble"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 5, "name": "Escuadradora", "generic": "Escuadradora", "category": "sierra", "icon": "📐", "color": "#2D5016", "desc": "Sierra de corte preciso para tableros grandes. Garantiza ángulos perfectos a 90° y cortes limpios.", "tags": ["Corte", "Precisión"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 6, "name": "Finger Joint", "generic": "Finger Joint Manual / Semiautomática", "category": "acabado", "icon": "🤝", "color": "#8B5E3C", "desc": "Une piezas de madera en forma de dedos. Aumenta la resistencia de la unión y optimiza el uso del material.", "tags": ["Unión", "Finger"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 7, "name": "Hidrómetro", "generic": "Medidor de Humedad para Madera", "category": "medicion", "icon": "💧", "color": "#185FA5", "desc": "Instrumento digital para medir el porcentaje de humedad en la madera. Fundamental para control de calidad.", "tags": ["Humedad", "Control", "Digital"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 8, "name": "Moldudera", "generic": "Moldudera", "category": "acabado", "icon": "🪚", "color": "#5C3D1E", "desc": "Máquina para perfilar y moldear bordes y cantos de piezas de madera. Permite crear molduras decorativas.", "tags": ["Moldura", "Perfil"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 9, "name": "Prensa de Platos Calientes", "generic": "Prensa de Platos Calientes", "category": "prensa", "icon": "🔥", "color": "#993C1D", "desc": "Prensa hidráulica con placas calefactoras para el pegado de chapas, melaminas y enchapados.", "tags": ["Prensa", "Calor", "Chapas"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 10, "name": "Prensa Inclinada", "generic": "Prensa para Ensamble", "category": "prensa", "icon": "🗜️", "color": "#BA7517", "desc": "Prensa de ensamble en ángulo para unir marcos, puertas y estructuras complejas de carpintería.", "tags": ["Prensa", "Ensamble", "Marco"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 11, "name": "Regruesadora", "generic": "Groseadora / Cepillo de Espesor", "category": "acabado", "icon": "📋", "color": "#C4956A", "desc": "Cepillo de espesor para dar grosor uniforme a las tablas. Permite trabajar piezas de distintas dimensiones.", "tags": ["Espesor", "Calibrado"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 12, "name": "Sierra Circular", "generic": "Sierra Circular", "category": "sierra", "icon": "⭕", "color": "#2D5016", "desc": "Sierra de disco para cortes longitudinales y transversales en madera maciza y tableros derivados.", "tags": ["Sierra", "Corte"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 13, "name": "Sierra Múltiple", "generic": "Múltiple", "category": "sierra", "icon": "🔀", "color": "#3B6D11", "desc": "Múltiples discos para corte simultáneo en varias piezas. Ideal para producción en serie y alta eficiencia.", "tags": ["Sierra", "Serie", "Industrial"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 14, "name": "Sierra Mural", "generic": "Sierra Vertical", "category": "sierra", "icon": "🗂️", "color": "#185FA5", "desc": "Sierra vertical para corte de tableros grandes en formato vertical. Requiere menos espacio de trabajo.", "tags": ["Sierra", "Vertical", "Tableros"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 15, "name": "Trozadora", "generic": "Despuntadora", "category": "sierra", "icon": "✂️", "color": "#639922", "desc": "Sierra de tronzar para cortar piezas a medida transversalmente. Ideal para despiece inicial de madera.", "tags": ["Trozar", "Despiece"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {"id": 16, "name": "Tupí", "generic": "Tupí", "category": "acabado", "icon": "🌀", "color": "#8B5E3C", "desc": "Fresadora vertical para perfilar bordes, ranuras y molduras. Herramienta versátil para acabados decorativos.", "tags": ["Fresado", "Perfil", "Moldura"], "estado": "", "origen": "", "precio_usd": None, "potencia": None, "peso": None, "velocidad": None, "capacidad": None, "imagen": None, "imagens": []},
    {
        "id": 17,
        "name": "Furadeira Automática",
        "generic": "Furadeira Automática com Múltiplos Cabeçotes",
        "category": "furadeira",
        "icon": "🔩",
        "color": "#2999dd",
        "desc": "Furadeira automática Lidear com múltiplos cabeçotes superiores e de topo. 32 mandris por cabeçote. Alta produtividade para furação em série em madeira e tableros.",
        "tags": ["Furadeira", "Automática", "Industrial"],
        "estado": "Usada",
        "origen": "Brasil",
        "precio_usd": None,
        "potencia": None,
        "peso": None,
        "velocidad": None,
        "capacidad": "32 mandris por cabeçote",
        "imagen": "/static/machine_17_2.jpg",
        "imagens": [
            "/static/machine_17_1.jpg",
            "/static/machine_17_2.jpg",
            "/static/machine_17_3.jpg",
        ],
        "destaque": True,
    },
]

FEATURED_MACHINE = next((m for m in MACHINES if m.get("destaque")), None)
